version: '3.9'

services:
  mysite:
    container_name: mysite
    build:
      context: mysite
      dockerfile: Dockerfile
      args:
        - MYSQL_USER=${MYSQL_USER} # mysql password from .env
        - MYSQL_PASSWORD=${MYSQL_PASSWORD} # mysql password from .env
    ports:
      - "80:80" # nginx
      - "3331:3306" # mysql
      - "3332:6379" # redis
    volumes:
        - ../:/app
        - ./mysite/php.ini:/etc/php/8.1/fpm/conf.d/php.ini
        - ./mysite/www.conf:/etc/nginx/conf.d/default.conf
        - ./mysite/mysqld.cnf:/etc/mysql/mysql.conf.d/extra.cnf

    # give access to /dev directory. Resolve many problem, like: lsof not show process, etc.
    privileged: true

    # fast stop
    stop_grace_period: 1s
    stop_signal: SIGKILL

